# Generated by Django 2.0 on 2022-06-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ANNUALData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('totalstu', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Annual placed Student Data',
            },
        ),
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=100)),
                ('totalstu1', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Company current year placed Student Data',
            },
        ),
        migrations.CreateModel(
            name='DepartmentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depatment', models.CharField(max_length=100)),
                ('totalstu2', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Departmentwise placed Student Data',
            },
        ),
    ]
