# Generated by Django 2.0 on 2022-06-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepartmentData',
            new_name='DepatmentData',
        ),
    ]
