# Generated by Django 2.2 on 2022-06-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0004_unplaceddata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagarydata',
            old_name='depatment',
            new_name='catagory',
        ),
    ]
