# Generated by Django 2.2 on 2022-06-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0005_auto_20220617_1705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catagaryData',
            new_name='CountryData',
        ),
        migrations.DeleteModel(
            name='ANNUALData',
        ),
        migrations.DeleteModel(
            name='CompanyData',
        ),
        migrations.DeleteModel(
            name='DepatmentData',
        ),
        migrations.DeleteModel(
            name='GenderData',
        ),
        migrations.DeleteModel(
            name='UnplacedData',
        ),
        migrations.AlterModelOptions(
            name='countrydata',
            options={'verbose_name_plural': 'Country Population Data'},
        ),
        migrations.RenameField(
            model_name='countrydata',
            old_name='catagory',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='countrydata',
            old_name='totalstu4',
            new_name='population',
        ),
    ]
