# Generated by Django 2.2 on 2022-06-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0006_auto_20220617_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('students', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Annual year placement report',
            },
        ),
        migrations.DeleteModel(
            name='CountryData',
        ),
    ]
