# Generated by Django 2.2 on 2022-06-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0007_auto_20220617_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategaryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categary', models.CharField(max_length=100)),
                ('students3', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Categarywise placement report',
            },
        ),
        migrations.CreateModel(
            name='companyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('students4', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Companywise placement report',
            },
        ),
        migrations.CreateModel(
            name='DepartmentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=100)),
                ('students2', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Departmentwise placement report',
            },
        ),
        migrations.CreateModel(
            name='GenderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
                ('students5', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Genderwise placement report',
            },
        ),
        migrations.CreateModel(
            name='PlacedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed', models.CharField(max_length=100)),
                ('students6', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'placed & unplaced placement report',
            },
        ),
        migrations.RenameField(
            model_name='annualdata',
            old_name='students',
            new_name='students1',
        ),
    ]
