# Generated by Django 2.2 on 2022-06-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0008_auto_20220617_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualdata',
            old_name='students1',
            new_name='students',
        ),
    ]
